[build]
builder = "nixpacks"

[deploy]
startCommand = "python google_legal_analyzer.py & node app.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 30

[nixpacks.setup]
aptPkgs = ["python3", "python3-pip"]

[nixpacks.install]
cmds = ["pip install -r requirements.txt", "npm install"]