[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 30

[nixpacks.setup]
providers = ["node", "python"]
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[nixpacks.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "npm install"
]

[nixpacks.start]
cmd = "python3 google_legal_analyzer.py & node app.js"