[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on-failure"

[[services]]
name = "web"
source = "."
buildCommand = "npm install"
startCommand = "node backend/static-server.js"

[services.variables]
NODE_ENV = "production"
PORT = "$PORT"

[[services]]
name = "worker"  
source = "."
buildCommand = "pip install -r requirements.txt"
startCommand = "python google_legal_analyzer.py"

[services.variables]
FLASK_ENV = "production"
